"""initial migration

Revision ID: feb00f81b827
Revises: 8d22f8c06400
Create Date: 2024-11-28 11:37:41.639041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb00f81b827'
down_revision = '8d22f8c06400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leavetypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_allocation', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requires_balance', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leavetypes', schema=None) as batch_op:
        batch_op.drop_column('requires_balance')
        batch_op.drop_column('default_allocation')

    # ### end Alembic commands ###
